### ISSUE TITLE
module importing error for web interface

### ISSUE THREAD

**Issue by xiuliren** [flatironinstitute/kvsstcp#5]
I am using disBatch, but got an error in the slurm.out file:

```
Traceback (most recent call last):
  File "/mnt/home/carriero/projects/disBatch/beta/disBatch/disBatch", line 12, in <module>
    disBatch.main()
  File "/mnt/home/carriero/projects/disBatch/beta/disBatch/disbatchc/disBatch.py", line 1908, in main
    from kvsstcp import wskvsmu
ImportError: cannot import name 'wskvsmu' from 'kvsstcp' (/mnt/home/jwu/opt/kvsstcp/kvsstcp.py)
```

I just noticed that this module is for web interface. I can disable the web interface for now.

**Comment by dylex** [comment]
This looks like a bug in the web support of disbatch, not kvsstcp.  I'm told the web stuff is not supported, and you should use the monitor instead.
